spring:
  application:
    name: skillmap
  datasource:
    url: jdbc:postgresql://localhost:5432/skillmap
    username: skillmap_user
    password: skillmap_pass
    driver-class-name: org.postgresql.Driver

server:
  port: 8080


