spring:
  application:
    name: skillmap
  datasource:
    url: jdbc:postgresql://localhost:5432/skillmap
    username: skillmap_user
    password: skillmap_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  port: 8080


